# --- GŁÓWNE USTAWIENIA ---
title: Tomasz Dunia - Blog
description: Blog o wszystkim - przemyślenia, poradniki, projekty otwarto-źródłowe, praca, self-hosting, seriale, filmy / Blog about everything - thoughts, tutorials, open-source projects, work, self-hosting, series, movies
url: "https://to3k.github.io" # do zmiany po przełączeniu domeny
baseurl: "" 

# --- MOTYW ---
remote_theme: riggraz/no-style-please

# MENU - To musi być tutaj, a nie w _data/menu.yml
menu:
  - title: Blog
    url: /
  - title: Archiwum
    url: /archive
  - title: GitHub
    url: https://github.com/to3k

# --- USTAWIENIA LINKÓW ---
permalink: /:title/

# --- WTYCZKI ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap

# --- DANE AUTORA ---
# Wyświetlają się w stopce motywu
author:
  name: Tomasz Dunia
  url: https://tomaszdunia.pl

# --- USTAWIENIA MARKDOWN ---
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
